apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /hello-foo(/|$)(.*)
            backend:
              service:
                name: hello-foo-service
                port:
                  name: http
          - pathType: Prefix
            path: /hello-bar(/|$)(.*)
            backend:
              service:
                name: hello-bar-service
                port:
                  name: http
          - pathType: Prefix
            path: /hello-baz(/|$)(.*)
            backend:
              service:
                name: hello-baz-service
                port:
                  name: http
